# Generated by Django 4.1 on 2025-01-21 07:02

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=200)),
                ('admin_lastname', models.CharField(max_length=200)),
                ('admin_phone', models.CharField(max_length=20, unique=True)),
                ('admin_password', models.CharField(max_length=200)),
                ('admin_sms_code', models.CharField(max_length=10, null=True)),
                ('admin_permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('other_information', models.JSONField()),
                ('admin_create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('admin_phone_number_validation', models.IntegerField(default=0)),
                ('admin_sms_code_start_time', models.DateTimeField(null=True)),
                ('admin_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=400), default=list, null=True, size=None)),
                ('admin_creator_id', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='StaticToken',
            fields=[
                ('token_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_name', models.CharField(max_length=200)),
                ('token', models.TextField()),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'StaticToken',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=200)),
                ('token', models.TextField()),
                ('other_information', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'Token',
            },
        ),
        migrations.CreateModel(
            name='MiddleAdmins',
            fields=[
                ('middle_admin_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Authorization.admins')),
                ('project_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('water_meter_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'MiddleAdmins',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200, null=True)),
                ('user_lastname', models.CharField(max_length=200, null=True)),
                ('user_phone', models.CharField(max_length=20, unique=True)),
                ('user_password', models.CharField(max_length=200, null=True)),
                ('user_sms_code', models.CharField(max_length=10, null=True)),
                ('user_profile', models.JSONField(null=True)),
                ('other_information', models.JSONField(null=True)),
                ('user_password_changed', models.IntegerField(default=0)),
                ('user_create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_phone_number_validation', models.IntegerField(default=0)),
                ('user_sms_code_start_time', models.DateTimeField(null=True)),
                ('user_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=400), default=list, null=True, size=None)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authorization.admins')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('permission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_persian_name', models.CharField(max_length=200, null=True)),
                ('permission_english_name', models.CharField(max_length=200, unique=True)),
                ('permission_description', models.TextField(null=True)),
                ('permission_create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authorization.admins')),
            ],
            options={
                'db_table': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='PermissionCategory',
            fields=[
                ('permission_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_category_persian_name', models.CharField(max_length=200, null=True)),
                ('permission_category_english_name', models.CharField(max_length=200, unique=True)),
                ('permission_category_description', models.TextField(null=True)),
                ('permission_category_create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authorization.admins')),
                ('permissions', models.ManyToManyField(to='Authorization.permissions')),
            ],
            options={
                'db_table': 'PermissionCategory',
            },
        ),
    ]
